language: node_js
node_js: stable
dist: trusty
sudo: required
addons:
  sauce_connect: true
before_script:
  - npm install -g bower polylint web-component-tester
  - bower install
  - polylint
script:
  - wct -s 'default'
