language: node_js
node_js: stable
dist: trusty
sudo: required
cache:
  directories:
    - bower_components
branches:
  only:
    - master
addons:
  firefox: latest
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
  sauce_connect: true
before_script:
  - npm install -g polymer-cli
  - polymer install --variants
script:
  - xvfb-run polymer test
  - if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then polymer test -s 'default'; fi
notifications:
  email: change
